-- MONITORING_DEPARTMENTS — Thru / For department lists (ISSD monitoring tools backend)
--
-- Run as the app Oracle user, or enable MONITORING_AUTO_DDL on startup.
--
-- KIND: 'thru' (routing) or 'for' (receiving)

SET DEFINE OFF;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MONITORING_DEPARTMENTS (
      ID          NUMBER(18)     PRIMARY KEY,
      NAME        VARCHAR2(100)  NOT NULL,
      KIND        VARCHAR2(10)   NOT NULL,
      IS_BUILTIN  NUMBER(1)      DEFAULT 0 NOT NULL,
      CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE UNIQUE INDEX MONITORING_DEPT_NAME_KIND_UK
      ON MONITORING_DEPARTMENTS (UPPER(NAME), KIND)
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-955, -1408) THEN
      RAISE;
    END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'MONITORING_DEPARTMENTS';
  IF v_cnt = 0 THEN
    RETURN;
  END IF;

  SELECT COUNT(*) INTO v_cnt FROM MONITORING_DEPARTMENTS;
  IF v_cnt > 0 THEN
    RETURN;
  END IF;

  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (1, 'NCD', 'thru', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (2, 'ITMG', 'thru', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (3, 'BAC', 'thru', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (4, 'PMO', 'thru', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (5, 'PSD', 'thru', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (6, 'PCEO', 'thru', 1);

  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (101, 'SSC', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (102, 'PCEO', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (103, 'NCD', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (104, 'ITMG', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (105, 'BAC', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (106, 'PMO', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (107, 'PSD', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (108, 'PPMD', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (109, 'BUDGET', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (110, 'LEGAL', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (111, 'ESD', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (112, 'OPSD', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (113, 'PMERD', 'for', 1);
  INSERT INTO MONITORING_DEPARTMENTS (ID, NAME, KIND, IS_BUILTIN) VALUES (114, 'LDD', 'for', 1);
  COMMIT;
END;
/
