-- MONITORING_POLICIES — Policy monitoring (under Outgoing Document Monitoring)
--
-- Run as the app Oracle user, or enable MONITORING_AUTO_DDL=1 on startup.

SET DEFINE OFF;

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE MONITORING_POLICIES (
      ID                NUMBER(18)      PRIMARY KEY,
      TRANSACTION_CODE  VARCHAR2(50)    NOT NULL,
      POLICY_TITLE      VARCHAR2(500)   NOT NULL,
      CREATED_BY        VARCHAR2(200)   NOT NULL,
      ASSIGNED_TO       VARCHAR2(200)   NOT NULL,
      START_DATE        DATE            NOT NULL,
      END_DATE          DATE            NOT NULL,
      DAYS_COUNT        NUMBER(10),
      STATUS_LABEL      VARCHAR2(50)    NOT NULL,
      REMARKS           VARCHAR2(2000),
      CREATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM user_tab_columns
   WHERE table_name = 'MONITORING_POLICIES' AND column_name = 'CREATED_AT';
  IF c = 0 THEN
    EXECUTE IMMEDIATE
      q'[ALTER TABLE MONITORING_POLICIES ADD (CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)]';
  END IF;

  SELECT COUNT(*) INTO c FROM user_tab_columns
   WHERE table_name = 'MONITORING_POLICIES' AND column_name = 'UPDATED_AT';
  IF c = 0 THEN
    EXECUTE IMMEDIATE
      q'[ALTER TABLE MONITORING_POLICIES ADD (UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)]';
  END IF;
END;
/
